[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "postgres", "uuid", "chrono"] }
jsonwebtoken = "9.3.1"
chrono = "0.4.39"
bcrypt = "0.17.0"
serde = "1.0.217"
uuid = "1.13.2"
serde_json = "1.0.138"