services:
  # PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: areum_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - areum_network

  # Actix Web Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: areum_backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - areum_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/target
    command: >
      sh -c "sqlx database setup &&
             cargo watch -x run"

volumes:
  db_data:

networks:
  areum_network:
    driver: bridge