# fly.toml app configuration file generated for backendareum on 2025-03-05T15:28:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backendareum'
primary_region = 'mad'

[build]
  dockerfile = "Dockerfile"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  APP_ENVIRONMENT = "production"
