name: Rust CI/CD backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
    test:
        name: Interaction with DB
        runs-on: ubuntu-latest
        # Service containers to run alongside the `test` container job
        services:
          postgres:
            # Docker Hub image
            image: postgres:14
            env:
              POSTGRES_USER: ${{secrets.POSTGRES_USER}}
              POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
              POSTGRES_DB: ${{secrets.POSTGRES_DB_NAME}}
            ports:
              - ${{vars.POSTGRES_PORT}}:5432
        
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          APP_USER: ${{ secrets.APP_USER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          APP_PORT: ${{ secrets.APP_PORT }}

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
    
            - name: Install the Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Install sqlx-cli
              run: |
                if ! command -v sqlx &> /dev/null; then
                  echo "sqlx not found, installing..."
                  cargo install sqlx-cli \
                  --version=${{ vars.SQLX_CLI_VERSION }} \
                  --features ${{ vars.SQLX_CLI_FEATURES }} \
                  --no-default-features \
                  --locked
                else
                  echo "sqlx-cli already installed, skipping installation."
                fi
                
                echo "Verifying sqlx installation"
                sqlx --version
  
            - name: Create app user in Postgres
              run: |
                sudo apt-get install postgresql-client

                # Wait for PostgreSQL to be ready
                for i in {1..10}; do
                  pg_isready -h localhost -p 5432 && break
                  echo "Waiting for PostgreSQL to be ready..."
                  sleep 2
                done
        
                # Create the application user
                CREATE_QUERY="CREATE USER ${APP_USER} WITH PASSWORD '${APP_USER_PW}';"
                PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -c "${CREATE_QUERY}"
        
                # Grant create db privileges to the app user
                GRANT_QUERY="ALTER USER ${APP_USER} CREATEDB;"
                PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -h "${POSTGRES_HOST}" -c "${GRANT_QUERY}"
            
            - name: Migrate database
              run: |
                SKIP_DOCKER=true ./scripts/init_db.sh

            - name: Generate SQLx prepare files
              env:
                  RUSTFLAGS: "-A warnings"
                  SQLX_OFFLINE: false
              run: |
                echo "Forcing SQLx prepare generation..."
                export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
                
                # List all source files with sqlx::query! macros
                #echo "Files containing sqlx queries:"
                #grep -r "sqlx::query" --include="*.rs" . || echo "No sqlx queries found"
                
                # Make sure schema is ready by re-running migrations
                #SKIP_DOCKER=true DATABASE_URL="$DATABASE_URL" ./scripts/init_db.sh
                
                # Generate prepare files with verbose output
                RUST_LOG=debug cargo sqlx prepare --workspace -- --all-targets
                
                # Verify files were created
                echo "Generated SQLx prepare files:"
                find .sqlx -type f | sort
                
                # Show contents of one prepare file as example
                if [ -d ".sqlx" ] && [ "$(find .sqlx -type f | wc -l)" -gt 0 ]; then
                  echo "Example prepare file content:"
                  head -n 20 "$(find .sqlx -type f | head -1)"
                else
                  echo "No prepare files were generated!"
                fi
                
                # Switch back to offline mode for subsequent steps
                export SQLX_OFFLINE=true
              
            - name: Run tests with explicit DATABASE_URL
              env:
                RUSTFLAGS: "-A warnings"
                SQLX_OFFLINE: true
                DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB_NAME }}
              run: cargo test --all

            - name: Check that queries are fresh
              env:
                RUSTFLAGS: "-A warnings"
              run: cargo sqlx prepare --workspace --check -- --all-targets